time_limit_solve = 300
memory_limit_solve = 4000

[[runners]]
name = "L_CPDDL"
path = "Training/training.sh"
kind = "Learn"
args = ["CPDDLMutexed"]
attribute = "P10"

[[runners]]
name = "S_CPDDL"
path = "Testing/testing-meta.sh"
kind = "Solve"
args = ["lama-first"]
depends = "L_CPDDL"
attribute = "downward"

[[runners]]
name = "Downward"
path = "Testing/testing.sh"
kind = "Solve"
args = ["lama-first"]
attribute = "downward"

[[attributes]]
name = "downward"
patterns = [
    { name = "total_time", pattern = "Total time: ([0-9.]*)" },
    { name = "search_time", pattern = "Search time: ([0-9.]*)" },
    { name = "peak_memory_translation", pattern = "Translator peak memory: ([0-9]*)" },
    { name = "peak_memory_search", pattern = "Peak memory: ([0-9]*)" },
    { name = "plan_length", pattern = "Plan length: ([0-9]*)" },
    { name = "states_generated", pattern = "Generated ([0-9]*)" },
    { name = "states_expanded", pattern = "Expanded ([0-9]*)" },
]

[[attributes]]
name = "P10"
patterns = [
    { name = "total_candidates", pattern = "Total candidates: ([0-9]*)" },
]

[[tasks]]
name = "barman-sat11-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/barman-sat11-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat11-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat11-strips/test/*.pddl"]

[[tasks]]
name = "barman-sat14-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/barman-sat14-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat14-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat14-strips/test/*.pddl"]

[[tasks]]
name = "blocksworld"
domain = "Dependencies/p10-benchmarks/Benchmarks/blocksworld/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/blocksworld/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/blocksworld/test/*.pddl"]

[[tasks]]
name = "childsnack-sat14-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/childsnack-sat14-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/childsnack-sat14-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/childsnack-sat14-strips/test/*.pddl"]

[[tasks]]
name = "depot"
domain = "Dependencies/p10-benchmarks/Benchmarks/depot/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/depot/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/depot/test/*.pddl"]

[[tasks]]
name = "driverlog"
domain = "Dependencies/p10-benchmarks/Benchmarks/driverlog/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/driverlog/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/driverlog/test/*.pddl"]

[[tasks]]
name = "ferry"
domain = "Dependencies/p10-benchmarks/Benchmarks/ferry/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/ferry/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/ferry/test/*.pddl"]

[[tasks]]
name = "floortile"
domain = "Dependencies/p10-benchmarks/Benchmarks/floortile/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/floortile/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/floortile/test/*.pddl"]

[[tasks]]
name = "grid"
domain = "Dependencies/p10-benchmarks/Benchmarks/grid/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/grid/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/grid/test/*.pddl"]

[[tasks]]
name = "gripper"
domain = "Dependencies/p10-benchmarks/Benchmarks/gripper/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/gripper/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/gripper/test/*.pddl"]

[[tasks]]
name = "logistics00"
domain = "Dependencies/p10-benchmarks/Benchmarks/logistics00/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/logistics00/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/logistics00/test/*.pddl"]

[[tasks]]
name = "logistics98"
domain = "Dependencies/p10-benchmarks/Benchmarks/logistics98/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/logistics98/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/logistics98/test/*.pddl"]

[[tasks]]
name = "miconic"
domain = "Dependencies/p10-benchmarks/Benchmarks/miconic/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/miconic/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/miconic/test/*.pddl"]

[[tasks]]
name = "mystery"
domain = "Dependencies/p10-benchmarks/Benchmarks/mystery/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/mystery/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/mystery/test/*.pddl"]

[[tasks]]
name = "nomystery-sat11-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/nomystery-sat11-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/nomystery-sat11-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/nomystery-sat11-strips/test/*.pddl"]

[[tasks]]
name = "rovers"
domain = "Dependencies/p10-benchmarks/Benchmarks/rovers/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/rovers/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/rovers/test/*.pddl"]

[[tasks]]
name = "satellite"
domain = "Dependencies/p10-benchmarks/Benchmarks/satellite/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/satellite/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/satellite/test/*.pddl"]

[[tasks]]
name = "sokoban"
domain = "Dependencies/p10-benchmarks/Benchmarks/sokoban/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/sokoban/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/sokoban/test/*.pddl"]

[[tasks]]
name = "spanner"
domain = "Dependencies/p10-benchmarks/Benchmarks/spanner/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/spanner/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/spanner/test/*.pddl"]

[[tasks]]
name = "tpp"
domain = "Dependencies/p10-benchmarks/Benchmarks/tpp/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/tpp/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/tpp/test/*.pddl"]

[[tasks]]
name = "transport-sat08-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/transport-sat08-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/transport-sat08-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/transport-sat08-strips/test/*.pddl"]

[[tasks]]
name = "transport-sat11-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/transport-sat11-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/transport-sat11-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/transport-sat11-strips/test/*.pddl"]

[[tasks]]
name = "transport-sat14-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/transport-sat14-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/transport-sat14-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/transport-sat14-strips/test/*.pddl"]

[[tasks]]
name = "zenotravel"
domain = "Dependencies/p10-benchmarks/Benchmarks/zenotravel/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/zenotravel/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/zenotravel/test/*.pddl"]
