time_limit_solve = 300
memory_limit_solve = 4000

[[runners]]
name = "L_CPDDL"
path = "Training/training.sh"
kind = "Learn"
args = ["CPDDLMutexed"]
attribute = "P10"

[[attributes]]
name = "P10"
patterns = [
    { name = "total_candidates", pattern = "Total candidates: ([0-9]*)" },
]

[[tasks]]
name = "barman-sat11-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/barman-sat11-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat11-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat11-strips/test/*.pddl"]

[[tasks]]
name = "barman-sat14-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/barman-sat14-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat14-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/barman-sat14-strips/test/*.pddl"]

[[tasks]]
name = "blocksworld"
domain = "Dependencies/p10-benchmarks/Benchmarks/blocksworld/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/blocksworld/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/blocksworld/test/*.pddl"]

[[tasks]]
name = "childsnack-sat14-strips"
domain = "Dependencies/p10-benchmarks/Benchmarks/childsnack-sat14-strips/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/childsnack-sat14-strips/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/childsnack-sat14-strips/test/*.pddl"]

[[tasks]]
name = "depot"
domain = "Dependencies/p10-benchmarks/Benchmarks/depot/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/depot/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/depot/test/*.pddl"]

[[tasks]]
name = "driverlog"
domain = "Dependencies/p10-benchmarks/Benchmarks/driverlog/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/driverlog/train/*.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/driverlog/test/*.pddl"]