[learn]
name = "L_CPDDL"
path = "Training/P10/bin/Release/net8.0/P10"
args = [["--generator"], ["CPDDLMutexed"], ["--domain DOMAIN"], ["--problems PROBLEMS"], ["--args cpddlOutput\\;DIR/Dependencies/p10-benchmarks/CPDDLGroups/TASK.txt"], ["--stackelberg-path DIR/Dependencies/modified-stackelberg-planner/src/fast-downward.py"], ["--fast-downward-path DIR/Dependencies/fast-downward/fast-downward.py"]]

[[tasks]]
name = "barman"
domain = "Dependencies/p10-benchmarks/Benchmarks/barman/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/barman/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/barman/usefulness/p*.pddl"]

[[tasks]]
name = "blocksworld"
domain = "Dependencies/p10-benchmarks/Benchmarks/blocksworld/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/blocksworld/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/blocksworld/usefulness/p*.pddl"]

[[tasks]]
name = "childsnack"
domain = "Dependencies/p10-benchmarks/Benchmarks/childsnack/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/childsnack/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/childsnack/usefulness/p*.pddl"]

[[tasks]]
name = "depots"
domain = "Dependencies/p10-benchmarks/Benchmarks/depots/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/depots/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/depots/usefulness/p*.pddl"]

[[tasks]]
name = "driverlog"
domain = "Dependencies/p10-benchmarks/Benchmarks/driverlog/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/driverlog/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/driverlog/usefulness/p*.pddl"]

[[tasks]]
name = "floortile"
domain = "Dependencies/p10-benchmarks/Benchmarks/floortile/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/floortile/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/floortile/usefulness/p*.pddl"]

[[tasks]]
name = "grid"
domain = "Dependencies/p10-benchmarks/Benchmarks/grid/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/grid/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/grid/usefulness/p*.pddl"]

[[tasks]]
name = "gripper"
domain = "Dependencies/p10-benchmarks/Benchmarks/gripper/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/gripper/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/gripper/usefulness/p*.pddl"]

[[tasks]]
name = "hiking"
domain = "Dependencies/p10-benchmarks/Benchmarks/hiking/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/hiking/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/hiking/usefulness/p*.pddl"]

[[tasks]]
name = "logistics"
domain = "Dependencies/p10-benchmarks/Benchmarks/logistics/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/logistics/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/logistics/usefulness/p*.pddl"]

[[tasks]]
name = "miconic"
domain = "Dependencies/p10-benchmarks/Benchmarks/miconic/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/miconic/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/miconic/usefulness/p*.pddl"]

[[tasks]]
name = "parking"
domain = "Dependencies/p10-benchmarks/Benchmarks/parking/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/parking/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/parking/usefulness/p*.pddl"]

[[tasks]]
name = "rovers"
domain = "Dependencies/p10-benchmarks/Benchmarks/rovers/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/rovers/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/rovers/usefulness/p*.pddl"]

[[tasks]]
name = "satellite"
domain = "Dependencies/p10-benchmarks/Benchmarks/satellite/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/satellite/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/satellite/usefulness/p*.pddl"]

[[tasks]]
name = "scanalyzer"
domain = "Dependencies/p10-benchmarks/Benchmarks/scanalyzer/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/scanalyzer/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/scanalyzer/usefulness/p*.pddl"]

[[tasks]]
name = "woodworking"
domain = "Dependencies/p10-benchmarks/Benchmarks/woodworking/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/woodworking/training/p*.pddl", "Dependencies/p10-benchmarks/Benchmarks/woodworking/usefulness/p*.pddl"]

