[learn]
name = "L_CPDDL"
path = "Training/P10/bin/Release/net8.0/P10"
args = [["--generator"], ["CPDDLMutexed"], ["--pre-usefulness-strategy"], ["UsedInPlans"], ["--post-usefulness-strategy"], ["UsedInPlansCombined"], ["--domain DOMAIN"], ["--problems PROBLEMS"], ["--args cpddlOutput\\;DIR/Dependencies/p10-benchmarks/CPDDLGroups/TASK.txt"], ["--stackelberg-path DIR/Dependencies/modified-stackelberg-planner/src/fast-downward.py"], ["--fast-downward-path DIR/Dependencies/fast-downward/fast-downward.py"]]

[solve]
name = "downward"
path = "Dependencies/fast-downward/fast-downward.py"
args = [["--alias"], ["lama-first"], ["DOMAIN", "LEARN_DIR/output/enhancedDomain.pddl"], ["PROBLEM"]]

[[tasks]]
name = "gripper"
domain = "Dependencies/p10-benchmarks/Benchmarks/gripper/domain.pddl"
learn = ["Dependencies/p10-benchmarks/Benchmarks/gripper/training/p1.pddl"]
solve = ["Dependencies/p10-benchmarks/Benchmarks/gripper/testing/*.pddl"]
