time_limit_solve = 300
memory_limit_solve = 4000

[[runners]]
name = "predicate"
path = "Training/training.sh"
kind = "Learn"
args = ["InvariantMetaActions"]

[[runners]]
name = "Fast Downward (Meta)"
path = "Testing/testing-meta.sh"
kind = "Solve"
args = ["lama-first"]
depends = "predicate"

[[runners]]
name = "Fast Downward"
path = "Testing/testing.sh"
kind = "Solve"
args = ["lama-first"]

[[tasks]]
name = "blocksworld"
domain = "Dependencies/learning-benchmarks/blocksworld/domain.pddl"
learn = "Dependencies/learning-benchmarks/blocksworld/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/blocksworld/testing/*/*.pddl"

[[tasks]]
name = "childsnack"
domain = "Dependencies/learning-benchmarks/childsnack/domain.pddl"
learn = "Dependencies/learning-benchmarks/childsnack/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/childsnack/testing/*/*.pddl"

[[tasks]]
name = "ferry"
domain = "Dependencies/learning-benchmarks/ferry/domain.pddl"
learn = "Dependencies/learning-benchmarks/ferry/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/ferry/testing/*/*.pddl"

[[tasks]]
name = "floortile"
domain = "Dependencies/learning-benchmarks/floortile/domain.pddl"
learn = "Dependencies/learning-benchmarks/floortile/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/floortile/testing/*/*.pddl"

[[tasks]]
name = "miconic"
domain = "Dependencies/learning-benchmarks/miconic/domain.pddl"
learn = "Dependencies/learning-benchmarks/miconic/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/miconic/testing/*/*.pddl"

[[tasks]]
name = "rovers"
domain = "Dependencies/learning-benchmarks/rovers/domain.pddl"
learn = "Dependencies/learning-benchmarks/rovers/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/rovers/testing/*/*.pddl"

[[tasks]]
name = "satellite"
domain = "Dependencies/learning-benchmarks/satellite/domain.pddl"
learn = "Dependencies/learning-benchmarks/satellite/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/satellite/testing/*/*.pddl"

[[tasks]]
name = "sokoban"
domain = "Dependencies/learning-benchmarks/sokoban/domain.pddl"
learn = "Dependencies/learning-benchmarks/sokoban/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/sokoban/testing/*/*.pddl"

[[tasks]]
name = "spanner"
domain = "Dependencies/learning-benchmarks/spanner/domain.pddl"
learn = "Dependencies/learning-benchmarks/spanner/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/spanner/testing/*/*.pddl"

[[tasks]]
name = "transport"
domain = "Dependencies/learning-benchmarks/transport/domain.pddl"
learn = "Dependencies/learning-benchmarks/transport/training/*/p0*.pddl"
solve = "Dependencies/learning-benchmarks/transport/testing/*/*.pddl"
